android:
  components:
  - tools
  - tools
  - platform-tools
  - android-19
  - android-22
  - android-23
  - android-25
  - build-tools-22.0.0
  - build-tools-22.0.1
  - build-tools-21.1.2
  - build-tools-23.0.1
  - build-tools-24.0.1
  - build-tools-24.0.2
  - build-tools-25.0.2
  - sys-img-armeabi-v7a-android-22
  - extra-android-m2repository
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
before_script: null
cache:
  directories:
  - $HOME/.m2
jdk: oraclejdk8
language: android
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: mvn clean install -Dandroid.device=test -B -U
sudo: false
